deploy:
  artifact: target/media-tracker-0.0.1.jar
branch-defaults:
  default:
    environment: friedflix-media-tracker
environment-defaults:
  friedflix-media-tracker:
    branch: null
    repository: null
global:
  application_name: friedflix-media-tracker
  default_ec2_keyname: null
  default_platform: Java
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
